backups:
  enabled: false
method: plugin
pluginConfiguration:
  name: barman-cloud.cloudnative-pg.io
  scheduledBackups:
    - name: daily-backup
      schedule: "0 0 0 * * *"
      backupOwnerReference: self
      method: plugin
      pluginConfiguration:
        name: barman-cloud.cloudnative-pg.io