---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: acme-contact
  namespace: cert-manager
spec:
  encryptedData:
    values.yaml: AgARkzjfmFkkMEjvkhz1Xe0U/WJbe5EaYHAGbIMCcjlaK+21mfuA8+hW4Dh9nZUuTgTOh29Ze2Hg+PkMsYsI8l+3G6HGsWYLurUoionU8n2Rdb1y2RJHFtoeH8cGhaIoIVOLi7QqlXjRN3UaFcuBFzVnELx8mTNg8O3fgFb3HFfH5yh9APE+xXqg2elKJ+IEjcrA5eS6U4yrwvdfUrkoJ1N6Fvl31fzP++Bgh1/o1RFKYJ2fDujPUCGDe2k95WrLkN9R1jW+FnQeRCEp3j2Gk0wpyW9zl35HDUHvcKZ9r1IhJ21o9krYeh21UrPQzKlqYXlNe8+bZ6j2ZsOvBDB7qWbJmWzrduxdnP1faiJGbTwu+gwcckoFn3bfw0tlhFLAvT5l7JGYhxoLxQrj56d+lM0FPdZdmo8YVXQcZfQXfhco9shPW+xmvVj5JK8Vif5YKymt8Wr4fLOuc48x7myFALW2T36KNwWCjFEjQgcAWct91oRcQZmB5UsZiJ9X+Sv0/zP3RwQUVnrpYmuBXnssf7xWciYAY0c4ZkOuv6G8KfF5VfB+WNtw/nKmyNQKxg+jZ+S6aEwHiEWzDxxQR3KdfIldiifSAQooBhaEuzAHsP3GE0tcRI53Tdeiv92xv0s1siun+aK4COGjEVzy76ANbVHLnGW/IkDjUJ3MTumOlNwFedpoytntZm/vzgIDbXnY5uZjxurohDn0whDAbQ8PX9h5wBM/vRpqF5/XsoaZgHlCqW/j+0o0UkLIe5o=
  template:
    metadata:
      name: acme-contact
      namespace: cert-manager
